const categories = {
    action: [
        {
            title: "Inception",
            imgSrc: "movie's posters/Inception.jpg",
            imdbRating: "8.8",
            year: "2010",
            duration: "2h 28min",
            description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
            country: "USA",
            genre: "Action, Adventure, Sci-Fi",
            director: "Christopher Nolan",
            writer: "Christopher Nolan",
            actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
            link: "https://www.imdb.com/title/tt1375666/"
        },
        {
            title: "Avengers",
            imgSrc: "movie's posters/Avengers.jpg",
            imdbRating: "8.0",
            year: "2012",
            duration: "2h 23min",
            description: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
            country: "USA",
            genre: "Action, Adventure, Sci-Fi",
            director: "Joss Whedon",
            writer: "Joss Whedon, Zak Penn",
            actors: "Robert Downey Jr., Chris Evans, Scarlett Johansson",
            link: "https://www.imdb.com/title/tt0848228/"
        },
        {
            title: "Batman",
            imgSrc: "movie's posters/Batman.jpg",
            imdbRating: "7.5",
            year: "1989",
            duration: "2h 6min",
            description: "The Dark Knight of Gotham City begins his war on crime with his first major enemy being the clownishly homicidal Joker.",
            country: "USA",
            genre: "Action, Adventure",
            director: "Tim Burton",
            writer: "Bob Kane, Sam Hamm",
            actors: "Michael Keaton, Jack Nicholson, Kim Basinger",
            link: "https://www.imdb.com/title/tt0096895/"
        },
        {
            title: "Gladiator",
            imgSrc: "movie's posters/Gladiator.jpg",
            imdbRating: "8.5",
            year: "2000",
            duration: "2h 35min",
            description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
            country: "USA, UK",
            genre: "Action, Adventure, Drama",
            director: "Ridley Scott",
            writer: "David Franzoni, John Logan, William Nicholson",
            actors: "Russell Crowe, Joaquin Phoenix, Connie Nielsen",
            link: "https://www.imdb.com/title/tt0172495/"
        }
        
    ],
    thriller:[
        {
            title: "Joker",
            imgSrc: "movie's posters/Joker.jpg",
            imdbRating: "8.4",
            year: "2019",
            duration: "2h 2min",
            description: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
            country: "USA",
            genre: "Crime, Drama, Thriller",
            director: "Todd Phillips",
            writer: "Todd Phillips, Scott Silver",
            actors: "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
            link: "https://www.imdb.com/title/tt7286456/"
        },
        {
            title: "Oppenheimer",
            imgSrc: "movie's posters/Oppenheimer.jpg",
            imdbRating: "8.4",
            year: "2023",
            duration: "3h",
            description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
            country: "USA",
            genre: "Biography, Drama, History",
            director: "Christopher Nolan",
            writer: "Christopher Nolan, Kai Bird, Martin Sherwin",
            actors: "Cillian Murphy, Emily Blunt, Matt Damon",
            link: "https://www.imdb.com/title/tt15398776/"
        }
    ],
    animation: [
        {
            title: "Inside Out",
            imgSrc: "movie's posters/InsideOut.jpg",
            imdbRating: "8.2",
            year: "2015",
            duration: "1h 35min",
            description: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.",
            country: "USA",
            genre: "Animation, Adventure, Comedy",
            director: "Pete Docter, Ronnie del Carmen",
            writer: "Pete Docter, Meg LeFauve, Josh Cooley",
            actors: "Amy Poehler, Bill Hader, Lewis Black",
            link: "https://www.imdb.com/title/tt2096673/"
        },
        {
            title: "Klaus",
            imgSrc: "movie's posters/Klaus.jpg",
            imdbRating: "8.1",
            year: "2019",
            duration: "1h 36min",
            description: "A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg's new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.",
            country: "Spain, USA",
            genre: "Animation, Adventure, Comedy",
            director: "Sergio Pablos, Carlos Martínez López",
            writer: "Sergio Pablos, Zach Lewis, Jim Mahoney",
            actors: "Jason Schwartzman, J.K. Simmons, Rashida Jones",
            link: "https://www.imdb.com/title/tt4729430/"
        },
        {
            title: "Toy Story",
            imgSrc: "movie's posters/ToyStory.jpg",
            imdbRating: "8.3",
            year: "1995",
            duration: "1h 21min",
            description: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
            country: "USA",
            genre: "Animation, Adventure, Comedy",
            director: "John Lasseter",
            writer: "John Lasseter, Pete Docter, Andrew Stanton",
            actors: "Tom Hanks, Tim Allen, Don Rickles",
            link: "https://www.imdb.com/title/tt0114709/"
        },
        {
            title: "Coco",
            imgSrc: "movie's posters/Coco.jpg",
            imdbRating: "8.4",
            year: "2017",
            duration: "1h 45min",
            description: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
            country: "USA",
            genre: "Animation, Adventure, Family",
            director: "Lee Unkrich, Adrian Molina",
            writer: "Lee Unkrich, Jason Katz, Matthew Aldrich",
            actors: "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt",
            link: "https://www.imdb.com/title/tt2380307/"
        },
        {
            title: "Wall-E",
            imgSrc: "movie's posters/WallE.jpg",
            imdbRating: "8.4",
            year: "2008",
            duration: "1h 38min",
            description: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
            country: "USA",
            genre: "Animation, Adventure, Family",
            director: "Andrew Stanton",
            writer: "Andrew Stanton, Pete Docter",
            actors: "Ben Burtt, Elissa Knight, Jeff Garlin",
            link: "https://www.imdb.com/title/tt0910970/"
        }/* ,
        {
            title: "Luca",
            imgSrc: "movie's posters/Luca.jpg",
            imdbRating: "7.5",
            year: "2021",
            duration: "1h 35min",
            description: "On the Italian Riviera, an unlikely but strong friendship grows between a human being and a sea monster disguised as a human.",
            country: "USA, Italy",
            genre: "Animation, Adventure, Comedy",
            director: "Enrico Casarosa",
            writer: "Enrico Casarosa, Jesse Andrews, Simon Stephenson",
            actors: "Jacob Tremblay, Jack Dylan Grazer, Emma Berman",
            link: "https://www.imdb.com/title/tt12801262/"
        } */
    ],
    drama: [
        {
            title: "Hacksaw Ridge",
            imgSrc: "movie's posters/HacksawRidge.jpg",
            imdbRating: "8.1",
            year: "2016",
            duration: "2h 19min",
            description: "WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.",
            country: "Australia, USA",
            genre: "Biography, Drama, History",
            director: "Mel Gibson",
            writer: "Robert Schenkkan, Andrew Knight",
            actors: "Andrew Garfield, Sam Worthington, Luke Bracey",
            link: "https://www.imdb.com/title/tt2119532/"
        },
        {
            title: "Forrest Gump",
            imgSrc: "movie's posters/ForrestGump.jpg",
            imdbRating: "8.8",
            year: "1994",
            duration: "2h 22min",
            description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
            country: "USA",
            genre: "Drama, Romance",
            director: "Robert Zemeckis",
            writer: "Winston Groom, Eric Roth",
            actors: "Tom Hanks, Robin Wright, Gary Sinise",
            link: "https://www.imdb.com/title/tt0109830/"
        },
        {
            title: "Green Mile",
            imgSrc: "movie's posters/GreenMile.jpg",
            imdbRating: "8.6",
            year: "1999",
            duration: "3h 9min",
            description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
            country: "USA",
            genre: "Crime, Drama, Fantasy",
            director: "Frank Darabont",
            writer: "Stephen King, Frank Darabont",
            actors: "Tom Hanks, Michael Clarke Duncan, David Morse",
            link: "https://www.imdb.com/title/tt0120689/"
        },
        {
            title: "The Shawshank Redemption",
            imgSrc: "movie's posters/TheShawshank.jpg",
            imdbRating: "9.3",
            year: "1994",
            duration: "2h 22min",
            description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
            country: "USA",
            genre: "Drama",
            director: "Frank Darabont",
            writer: "Stephen King, Frank Darabont",
            actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
            link: "https://www.imdb.com/title/tt0111161/"
        },
        {
            title: "12 Angry Men",
            imgSrc: "movie's posters/12AngryMen.jpg",
            imdbRating: "9.0",
            year: "1957",
            duration: "1h 36min",
            description: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
            country: "USA",
            genre: "Drama",
            director: "Sidney Lumet",
            writer: "Reginald Rose",
            actors: "Henry Fonda, Lee J. Cobb, Martin Balsam",
            link: "https://www.imdb.com/title/tt0050083/"
        },
        
    ],
    fantasy: [
        
        {
            title: "The Lord of the Rings: The Fellowship of the Ring",
            imgSrc: "movie's posters/LOR.jpg",
            imdbRating: "8.8",
            year: "2001",
            duration: "2h 58min",
            description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
            country: "New Zealand, USA",
            genre: "Action, Adventure, Drama",
            director: "Peter Jackson",
            writer: "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
            actors: "Elijah Wood, Ian McKellen, Orlando Bloom",
            link: "https://www.imdb.com/title/tt0120737/"
        }],
        comedy:[
        {
            title: "Catch Me If You Can",
            imgSrc: "movie's posters/CatchMeIfYouCan.jpg",
            imdbRating: "8.1",
            year: "2002",
            duration: "2h 21min",
            description: "The story of a young man who runs away from home and successfully forges millions of dollars in checks.",
            country: "USA",
            genre: "Biography, Crime, Drama",
            director: "Steven Spielberg",
            writer: "Jeff Nathanson, Frank Abagnale Jr.",
            actors: "Leonardo DiCaprio, Tom Hanks, Christopher Walken",
            link: "https://www.imdb.com/title/tt0264464/"
        }
    ]
}